### ISSUE TITLE
UI Tracker

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/landsat8.earth#34]
- [ ] Select bands. Good list of defaults: https://eos.com/ndwi/
- [x] Manner of band combination/spectral index
- [x] Colormap chooser
- [x] Choice of prebuilt mosaics
- [ ] Choice of custom mosaics?
- [x] Visualize available colormaps in list

**Comment by kylebarron** [comment]
As of https://github.com/kylebarron/landsat8.earth/commit/e2582cf84fb062c9ddb8379d9df663808e61d5fb, UI is "decently usable", though of course not polished.
